---
clone:
  depth: 1
kind: pipeline
name: windows amd64 build
platform:
  os: windows
pull: always
steps:
- commands:
  - windows/build.ps1
  - windows/package.ps1
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: build
  when:
    event:
    - push
- commands:
  - windows/build.ps1
  - windows/package.ps1
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.ps1 windows windows amd64 100.0.0+${DRONE_COMMIT_SHA:0:8}
    ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: copy build
  volumes: []
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.ps1 windows windows amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-builder
  name: copy relase
  volumes: []
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes: []
---
clone:
  depth: 1
depends_on:
- windows amd64 build
kind: pipeline
name: windows index
platform:
  os: windows
pull: always
steps:
- commands:
  - Get-ChildItem -Recurse windows
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/msi-builder
  name: index build
  volumes: []
  when:
    event:
    - push
- commands:
  - Get-ChildItem -Recurse windows
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/msi-builder
  name: index release
  volumes: []
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes: []
---
clone:
  depth: 1
depends_on:
- windows index
kind: pipeline
name: windows amd64 test
platform:
  os: windows
pull: always
steps:
- commands:
  - windows/testpackage.ps1 100.0.0+${DRONE_COMMIT_SHA:0:8}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-tester
  name: test build
  volumes: []
  when:
    event:
    - push
- commands:
  - windows/testpackage.ps1 ${DRONE_TAG}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/windows-tester
  name: test release
  volumes: []
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes: []
---
kind: signature
hmac: 295addb318387359252ae045071c4d560d943349137370395ab66bb18a8480c8

...
